name: GetRusty

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build rust_first
        run: cargo build --verbose --manifest-path projects/rust_first/Cargo.toml

      - name: Run tests for rust_first
        run: cargo test --verbose --manifest-path projects/rust_first/Cargo.toml

      - name: Build guess_game
        run: cargo build --verbose --manifest-path projects/guess_game/Cargo.toml

      - name: Run tests for guess_game
        run: cargo test --verbose --manifest-path projects/guess_game/Cargo.toml
